# Generated by Django 6.0 on 2026-02-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('posts', models.ManyToManyField(blank=True, related_name='Tags', to='blog.post')),
            ],
        ),
    ]
